services:
    app:
        container_name: app-todo-list
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            args:
                USER: laravel
                UID: 1000
                PORT: 9000
                WORKDIR: /var/www

        volumes:
            -  .:/var/www
            - ./storage:/var/www/storage
            - ./bootstrap/cache:/var/www/bootstrap/cache
        ports:
            - "9000:9000"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        depends_on:
            - db


    nginx:
        container_name: nginx-todo-list
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: mysql-todo-list
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - db
volumes:
    dbdata:
